language: go 
go: '1.9' 
before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update -y
  - sudo apt-get install solc -y
  - ln -s $GOPATH/src/github.com/sec-bit/minievm $GOPATH/src/minievm
